### ISSUE TITLE
Same order of colors returned

### ISSUE THREAD

**Issue by rezasham** [bachonk/UIImageView-Letters#15]
Hi,

Seems like same order of random colors are generated each time the view loads. You need to seed drand48.

srand48(arc4random());

see apple doc as they also suggest initializing it: https://developer.apple.com/library/ios/documentation/System/Conceptual/ManPages_iPhoneOS/man3/srand48.3.html

**Comment by bachonk** [comment]
Good call. This is available as of the `1.1.3` release.
