### ISSUE TITLE
How to use this with swift?

### ISSUE THREAD

**Issue by neelamsharma12** [bachonk/UIImageView-Letters#17]

**Comment by bachonk** [comment]
Hey Neelam,

You're going to need to create a bridging header as you would with any other Objective-C / Swift hybrid project.

You can find the official Apple docs [here](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html), and a helpful StackOverflow answer [here](http://stackoverflow.com/questions/24002369/how-to-call-objective-c-code-from-swift)

**Comment by neelamsharma12** [comment]
@bachonk  Thank you so much. It worked for me..:)
