### ISSUE TITLE
UITableView Error

### ISSUE THREAD

**Issue by williamkurniawan** [bachonk/UIImageView-Letters#18]
![simulator screen shot feb 17 2016 6 12 32 pm](https://cloud.githubusercontent.com/assets/16736202/13107805/0fac0eea-d5a2-11e5-9fec-fae67e5108ad.png)

**Comment by bachonk** [comment]
Could you post some relevant code from your `cellForRowAtIndexPath` method?

**Comment by bachonk** [comment]
Closing this as cannot reproduce.
