### ISSUE TITLE
Swift 3 update

### ISSUE THREAD

**Issue by netbe** [bachonk/UIImageView-Letters#21]
Any plan to support Swift 3.0?

**Comment by alexsanderkhitev** [comment]
@netbe Hello!
I think the upgrade will not be because the library is not updated for a long time

**Comment by bachonk** [comment]
There is a full rewrite in Swift 3 that should be available soon. Most likely will be in its own repo.

**Comment by bachonk** [comment]
Hey guys, you can now use the Swift 3 compatible lib here:
https://github.com/bachonk/InitialsImageView
